# This file configures the Dart analyzer to check for potential issues,
# enforce coding standards, and apply best practices in your Flutter project.

# Include Flutter's recommended lint rules.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # --- General Dart Rules ---
    prefer_single_quotes: true           # Prefer single quotes for strings
    avoid_print: true                    # Avoid using print (use logging instead)
    always_use_package_imports: true     # Use package: imports even internally
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    await_only_futures: true
    unnecessary_await_in_return: true

    # --- Flutter-specific Rules ---
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    use_key_in_widget_constructors: true
    avoid_unnecessary_containers: true

    # --- Best Practices ---
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    avoid_returning_null_for_future: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    always_declare_return_types: true

# For full list of rules: https://dart.dev/lints
